//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Album = new HashSet<Order_Album>();
        }
    
        public int ID { get; set; }
        public string IDUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Money { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Order_Album> Order_Album { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
