//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Album
    {
        public int IDOrder { get; set; }
        public int IDAlbum { get; set; }
        public Nullable<int> Quality { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Order Order { get; set; }
    }
}
