//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Albums = new HashSet<Album>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string FileType { get; set; }
        public string LinkSong { get; set; }
        public Nullable<int> IDGenre { get; set; }
        public Nullable<int> IDSinger { get; set; }
        public Nullable<int> IDComposer { get; set; }
    
        public virtual Composer Composer { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Singer Singer { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
    }
}
